### ISSUE TITLE
The package installed by pip is not complete. 

### ISSUE THREAD

**Issue by 13958806684** [EagleLab-ZJU/DGLD#106]
I installed DGLD by "pip install DGLD" and want to import the class GraphNodeAnomalyDectionDataset, but it raised ModuleNotFoundError. I checked the package installed and found there are only a few parts of the DGLD packages compared to whole project in this git repository. Maybe the packages installed by pip need to be updated.

**Comment by Arlen-yuzu** [comment]
Thanks for your suggestion. We have release DGLD version 0.3.0 on pypi to keep the package‘s content up to date with the latest version of the development version. You can use "pip install DGLD" or "pip install --upgrade DGLD" to get the latest version. And we have renewed the quick start part of the README file of the project. You can add code "from DGLD.utils.dataset import GraphNodeAnomalyDectionDataset" to import the class GraphNodeAnomalyDectionDataset.

**Comment by Arlen-yuzu** [comment]
> I installed DGLD by "pip install DGLD" and want to import the class GraphNodeAnomalyDectionDataset, but it raised ModuleNotFoundError. I checked the package installed and found there are only a few parts of the DGLD packages compared to whole project in this git repository. Maybe the packages installed by pip need to be updated.

Thanks for your suggestion. We have release DGLD version 0.3.0 on pypi to keep the package‘s content up to date with the latest version of the development version. You can use "pip install DGLD" or "pip install --upgrade DGLD" to get the latest version. And we have renewed the quick start part of the README file of the project. You can add code "from DGLD.utils.dataset import GraphNodeAnomalyDectionDataset" to import the class GraphNodeAnomalyDectionDataset.
